### PR TITLE
Add Support for Node v4.2 in travis.yml

### PR DESCRIPTION
**Pull request by galk-in**
We don't run test on 4.2 version. In this PR I added checking 4.2 version with correct CI flow in travis

### CODE REVIEW

**Comment by plroebuck** [comment]
Shouldn't do that. See this [StackOverflow response](http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline) for rationale. And you missed my initial point -- this change adds `.idea` back when your previous commit removed it (i.e., you didn't merge your previous change before making this one).

**Comment by plroebuck** [comment]
Why is `CXX` specified for this CI flow when not done for any others?

**Comment by galk-in** [comment]
> Why is CXX specified for this CI flow when not done for any others?
We need CXX only for 4 version. Check the [doc](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements).

**Comment by galk-in** [comment]
About changes in .gitignore - I will do it in different PR

**Pull request merged**
