### PR TITLE
updated contribution text

### PR DESCRIPTION
**Pull request by sichvoge**
As discussed in #227, this is an update for the contribution text.

### CODE REVIEW

**Comment by sichvoge** [comment]
@cybertk can you check, seems like there was a time out during the travis run.

**Comment by plroebuck** [comment]
No one noticed that steps 2 and 3 got merged into same line?

Ensure lines in README do not exceed 80 characters.

Add "[ci skip]" on standalone line within your commit message for documentation updates.
Don't waste machine cycles with unnecessary testing when no source/config files changed.

**Comment by sichvoge** [comment]
Done, thanks @plroebuck - learned something new today ;)

**Comment by sichvoge** [comment]
Done.

**Pull request merged**
