### PR TITLE
Ensure code style with coffeelint

### PR DESCRIPTION
**Pull request by cybertk**
Trying to enforce code style on CI, in order to collaborate better

### CODE REVIEW

**Comment by cybertk** [comment]
Can some help fix all lint errors to make this PR green?

**Comment by galk-in** [comment]
I changed default rule about max_length. I think length 120 symbols is the best. @ProLoser @cybertk what do you think?

**Comment by cybertk** [comment]
120 is ok for me

**Comment by cybertk** [comment]
@galk-in  Can we use a config file to keep customization, which the editors will respect

**Comment by galk-in** [comment]
@cybertk Yes. PR is very short, so I changed this with amend commit.

**Comment by ProLoser** [comment]
Don't care lol.

**Pull request merged**
