### PR TITLE
Feature/query

### PR DESCRIPTION
**Pull request by misfitdavidl**
i make  abao  can parses  request queryParams from raml queryParameters sections.
https://github.com/cybertk/abao/issues/28

### CODE REVIEW

**Comment by cybertk** [comment]
Sounds good, can someone verify this?

**Comment by ProLoser** [comment]
Should this use default?

**Comment by plroebuck** [comment]
On the face of it, this *seems* like an excellent feature addition. But as the number of optional qparams increases, the number of possible combinations grows exponentially, of which some combinations may be either mutually exclusive or nonsensical. And that doesn't even begin to handle [repeated qparams](http://stackoverflow.com/questions/24059773/correct-way-to-pass-multiple-values-for-same-parameter-name-in-get-request).

It may be slightly better than our current default (none) if we were to add qparams with the
```required: true``` attribute using the ```example``` value from RAML, at the expense of invalidating
(aka, breaking) any existing tests in the wild that were currently checking for missing req'd qparams.

If we can only have one test for the resource, is *ALL* qparams that much more revealing than *NONE*?
I'd much prefer some means to control which qparams are tested via hooks.

Even without the obvious prerequisite (multiple tests/resource) being available (when?),
I would recommend we block this addition until more thought is applied to its ramifications.

@ProLoser, don't understand your question.

**Comment by ProLoser** [comment]
The default value property

**Comment by plroebuck** [comment]
@ProLoser, I'd use ```example``` as primary, and ```default``` as backup if primary not provided.
Not sure what, if anything, could be used if neither is provided in RAML. Both *could* be used
if multiple tests/resource worked, but for the reasons stated above, don't think **abao** should
be automated this way for tests of qparams -- not a [monkey tester](https://en.wikipedia.org/wiki/Monkey_test).

**Comment by liweinan0423** [comment]
@plroebuck 

> On the face of it, this seems like an excellent feature addition. But as the number of optional qparams increases, the number of possible combinations grows exponentially, of which some combinations may be either mutually exclusive or nonsensical. 

Theoretically it is not a good idea to use query parameters in RESTful API, which is not semantic. However the reality is that some legacy code base has already done that. I think a compromise should be we let abao appending only `required query parameters`, leaving the liberty of appending optional and repeated qparams in `hookfiles`.

**Comment by cybertk** [comment]
@liweinan0423 Could you help rebase this PR, then I can merge it.

**Comment by liweinan0423** [comment]
@cybertk  I have created another pull request which has been rebased with master branch.

https://github.com/cybertk/abao/pull/154

@misfitdavidl Could you remove your branch `feature/query` as I have rebased this branch onto master branch, so the history in your branch has been changed.

**Comment by cybertk** [comment]
In favor of PR #155

**Pull request closed without merging**
