### PR TITLE
Load file refs

### PR DESCRIPTION
**Pull request by coltonlw**
This PR adds support for automatically resolving file $ref's in jsonschema.

Relative file $ref's may optionally resolved relative to the current working directory of the abao process.  This behavior must be enabled by passing the --load-file-refs option

Replaces PR #163 and #165 

Copied from #165:

This does not properly resolve $ref's relative to the referring document, for that the RAML parser must pass the path of the schema file that was !included or the path to the RAML file for an inline schema. That path needs to be fed to the $ref parser as the starting resolution scope. In the future, the RAML parser could be updated to provide de-referencing as a feature so this functionality can work. In the meantime, this PR allows projects using relative file paths in $ref's to work with abao, as is not currently possible with --schemas option. The limitation is all $ref's which are relative $ref's must be relative to the working directory of abao.  

EDIT:  The new behavior is optional, disabled by default, and can be enabled with the --load-file-refs CLI option.  A test for this option was added and the old tests for --schemas left in place.   Thanks @plroebuck and @cybertk for your time on this issue and I look forward to your feedback!

### CODE REVIEW

**Comment by coltonlw** [comment]
Coveralls is mad but I did add tests for my feature

**Comment by cybertk** [comment]
@coltonlw, thanks for your contribution. It looks you missed some unit test about `test.coffee`.

**Comment by cybertk** [comment]
And I prefer set the default value of `--load-file-refs` to true.

**Comment by cybertk** [comment]
What about `--expand-refs-auto`? Instead of `--load-file-refs`. As it's expanding the **$refs** automatically.

**Comment by plroebuck** [comment]
So am I missing something? This all started off with the complaint that `tv4` was somehow not compliant with the spec (debatable). But this PR is wholly non-compliant as it doesn't either. If we're going this route (replacing the working cmdline arg solution we already have), why **doesn't** this address your original complaint? Why would you use **abao**'s current directory instead of the RAML file's directory so you *could* get the filesystem resolution?

If this style is to replace the existing one, then let's just do it and withdraw our existing
`--schemas` cmdline argument. We should do one **or** the other... not both.

**Comment by coltonlw** [comment]
@plroebuck I understand what your saying, that the original PR gave the reasoning of parsing the $ref's relative the to referring document and this doesn't, so what's the point?  The thing is if the schemas are split into multiple directories, --schemas doesn't seem to work.  I tried @cybertk suggestion of "-s raml/schemas/**/*.json" and that didn't do it.  I think the problem is the $ref's have relative paths like "../definitions/user.json" where as --schemas sets the schema key / injected path to just the filename.  If I'm wrong about this please correct me as I would prefer to use the existing behavior and not make changes.  

I also think enabling this behavior by default is a mistake as builds using the --schemas argument who have $ref's that can't be resolved by json-schema-ref-parser but which are later injected by TV4 will break.  I know that parsing the $ref's as intended is possible, when that feature is added I think both of these options should be removed.  

@plroebuck After reading [RFC 1738](https://tools.ietf.org/html/rfc1738#section-3.10) I think relative file $ref's are also a made up convention so I understand what you're saying, but it's a useful thing to do and supported by the raml-api-workbench.

**Comment by plroebuck** [comment]
> I tried @cybertk suggestion of "-s raml/schemas/*/.json" and that didn't do it. 

Use `--schemas raml/schemas/**/*.json` so your subdirectories are glob'd

**Comment by coltonlw** [comment]
@plroebuck that's what I ran, github formatting just made it look wrong

**Comment by cybertk** [comment]
I agree @plroebuck 's opinion, let's do one or the other... not both.

**Comment by coltonlw** [comment]
Since what I have implemented here is not the final solution and parses local filesystem $ref's relative the the CWD of abao process, I don't think we should merge this. I'd much rather see the new behavior be parsing the $ref's the same way as the mulesoft atom api-workbench addon, which will keep behavior consistent.    See:  #177

**Pull request closed without merging**
