### PR TITLE
Tests fixed

### PR DESCRIPTION
**Pull request by abartomeu**
- Gruntfile changed to include the new lib folder
- Added grunt-contrib-watch as it was required
- Lint errors fixed
- Switch to load-grunt-config to fix a segfault

### CODE REVIEW

**Comment by galk-in** [comment]
👍 
@plroebuck @cybertk what do you think?

**Comment by plroebuck** [comment]
@abartomeu, could you split this PR into two separate ones, one for Grunt-related changes and the other for lint-related ones? This PR title seems kinda misleading -- not tests were actually fixed. And is there any detail about why the change from `jit-grunt` is necessary? Had wondered about the "src" directory part, but as I don't use Grunt myself, I left it alone (but nothing *new* about "lib" folder outside its addition to project's `Gruntfile`). Submit the PRs to **v0.4.0-beta.9** branch instead of **master**!

**Comment by jbunton** [comment]
Hi @plroebuck, thanks for looking at this :)

After a fresh clone, running `npm install && grunt test` we get 17 errors. I'm using Node v6.2.1 and NPM 3.9.5. @abartomeu has the same problem.

In order to get a successful run of `grunt test` locally we needed to fix these issues:

1. `grunt-contrib-watch` is used in the `Gruntfile` but not present in `package.json`
2. The `Gruntfile` is pointing to `src`, when all the code seems to be in `lib`. 
3. Node failed with a segmentation fault until I replaced `jit-git` with `load-grunt-config`. These appear to be functionally equivalent as far as Abao is concerned.
4. Linting errors uncovered by the path `src` -> `lib` path fixup

We'd be happy to split up the PR into two if you like. We can do one for the grunt fixes, including (1, 2, 3). Then a separate linting fix which includes only (4). In order to get a green build on the first change we can leave the linter disabled. Does that sound ok?


For reference here are the test failures I see when running `grunt test` on master.

```
  1) Test Runner #run when test is valid "before all" hook:
     TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at TestRunner.run (lib/test-runner.js:197:23)
    at Context.<anonymous> (test/unit/test-runner-test.coffee:101:16)
  

  2) Test Runner #run when test is valid should generate beforeAll hooks:
     AssertionError: expected false to be truthy
    at Function.assert.isOk (node_modules/chai/lib/chai/interface/assert.js:85:31)
    at Context.<anonymous> (test/unit/test-runner-test.coffee:118:16)
  

  3) Test Runner #run when test is valid should run mocha:
     AssertionError: expected false to be truthy
    at Function.assert.isOk (node_modules/chai/lib/chai/interface/assert.js:85:31)
    at Context.<anonymous> (test/unit/test-runner-test.coffee:122:16)
  

  4) Test Runner #run when test is valid should invoke callback with failures:
     AssertionError: expected stub to have been called with arguments null, 0
    stub(function () {}) at Context.<anonymous> (test/unit/test-runner-test.coffee:58:9)
  at 
  ontext.<anonymous> (test/unit/test-runner-test.coffee:125:31)
  

  5) Test Runner #run when test is valid should generate mocha suite:
     AssertionError: expected 0 to equal 1
    at Context.<anonymous> (test/unit/test-runner-test.coffee:129:16)
  

  6) Test Runner #run when test is valid should generate mocha test:
     TypeError: Cannot read property 'tests' of undefined
    at Context.<anonymous> (test/unit/test-runner-test.coffee:133:45)
  

  7) Test Runner #run when test is valid should generate hook of suite:
     TypeError: Cannot read property 'called' of undefined
    at Context.<anonymous> (test/unit/test-runner-test.coffee:138:38)
  

  8) Test Runner #run Interact with #test "before all" hook:
     TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at TestRunner.run (lib/test-runner.js:197:23)
    at test/unit/test-runner-test.coffee:177:18
    at mute (node_modules/mute/index.js:46:18)
    at Context.<anonymous> (test/unit/test-runner-test.coffee:176:9)
  

  9) Test Runner #run when test has no response code "before all" hook:
     TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at TestRunner.run (lib/test-runner.js:197:23)
    at Context.<anonymous> (test/unit/test-runner-test.coffee:203:16)
  

  10) Test Runner #run when test skipped in hooks "before all" hook:
     TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at TestRunner.run (lib/test-runner.js:197:23)
    at Context.<anonymous> (test/unit/test-runner-test.coffee:242:16)
  

  11) Test Runner #run when test has no response schema "before all" hook:
     TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at TestRunner.run (lib/test-runner.js:197:23)
    at Context.<anonymous> (test/unit/test-runner-test.coffee:278:16)
  

  12) Test Runner #run when test throws AssertionError "before all" hook:
     TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at TestRunner.run (lib/test-runner.js:197:23)
    at test/unit/test-runner-test.coffee:324:18
    at mute (node_modules/mute/index.js:46:18)
    at Context.<anonymous> (test/unit/test-runner-test.coffee:323:9)
  

  13) Test Runner #run when beforeAllHooks throws UncaughtError "before all" hook:
     TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at TestRunner.run (lib/test-runner.js:197:23)
    at test/unit/test-runner-test.coffee:365:18
    at mute (node_modules/mute/index.js:46:18)
    at Context.<anonymous> (test/unit/test-runner-test.coffee:364:9)
  

  14) Test Runner #run with options list all tests with `names` "before all" hook:
     TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at TestRunner.run (lib/test-runner.js:197:23)
    at test/unit/test-runner-test.coffee:401:18
    at mute (node_modules/mute/index.js:46:18)
    at Context.<anonymous> (test/unit/test-runner-test.coffee:400:9)
  

  15) Test Runner #run with options add additional headers with `headers` "before all" hook:
     TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at TestRunner.run (lib/test-runner.js:197:23)
    at Context.<anonymous> (test/unit/test-runner-test.coffee:441:16)
  

  16) Test Runner #run with options run test with hooks only indicated by `hooks-only` "before all" hook:
     TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at TestRunner.run (lib/test-runner.js:197:23)
    at Context.<anonymous> (test/unit/test-runner-test.coffee:487:16)
  

  17) Test Runner #run with options run test with hooks only indicated by `hooks-only` "after all" hook:
     TypeError: Cannot read property 'restore' of undefined
    at Context.<anonymous> (test/unit/test-runner-test.coffee:492:26)
```

**Comment by plroebuck** [comment]
@jbunton, sounds good. Had already looked over the changes and have no problems with them (just wanted to know more about the `jit-grunt` -> `load-grunt-config` one). I'll apply them back-to-back, so not as concerned about staying green the entire time. Primarily concerned with doing PRs to branch instead of master, and having good descriptions about why we made the changes.

Thanks for pointing out the problem (and fixing it).

**Comment by abartomeu** [comment]
Continued in #147.

Thanks you all for your comments.

**Pull request closed without merging**
