### PR TITLE
Add Node.js 5 version in travis.yml

### PR DESCRIPTION
**Pull request by galk-in**

### CODE REVIEW

**Comment by cybertk** [comment]
I think we don't need the following part to make CI green,

```
       env: NODE_ENV=development CXX=g++-4.8
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-4.8
```

**Comment by galk-in** [comment]
If you are sure that our dependencies will never use the native modules, then we don't need. I prefer use this approach for CI in my projects.

**Comment by cybertk** [comment]
I think we need give our users a hint (maybe in README) if we need something special like `CXX=g++-4.8`

**Comment by galk-in** [comment]
Now we don't need. But it can be in the future. Also it can be in develop dependency.

If you want i can change PR and remove CXX=g++-4.8

**Comment by cybertk** [comment]
It make sense, your call @galk-in

**Comment by galk-in** [comment]
@cybertk Done

**Comment by proebuck** [comment]
Put the two cases back in descending numeric order. Test from newest to oldest node version.

**Comment by galk-in** [comment]
@proebuck thx for idea. Done

**Pull request merged**
